// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tuan3.Context;


#nullable disable

namespace tuan3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tuan3.models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            ClassCode = "cntt01",
                            ClassName = "công nghệ thông tin 1"
                        },
                        new
                        {
                            ClassID = 2,
                            ClassCode = "cntt02",
                            ClassName = "công nghệ thông tin 2"
                        },
                        new
                        {
                            ClassID = 4,
                            ClassCode = "cntt03",
                            ClassName = "công nghệ thông tin 3"
                        },
                        new
                        {
                            ClassID = 5,
                            ClassCode = "cntt04",
                            ClassName = "công nghệ thông tin 4"
                        },
                        new
                        {
                            ClassID = 6,
                            ClassCode = "cntt05",
                            ClassName = "công nghệ thông tin 5"
                        },
                        new
                        {
                            ClassID = 7,
                            ClassCode = "cntt06",
                            ClassName = "công nghệ thông tin 6"
                        });
                });

            modelBuilder.Entity("tuan3.models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("ClassID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            BirthDate = new DateTime(2005, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 1,
                            Email = "an.nv@uneti.com",
                            FullName = "Nguyễn Hữu Quang",
                            Gender = true,
                            StudentCode = "SV01"
                        },
                        new
                        {
                            StudentID = 2,
                            BirthDate = new DateTime(2003, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 4,
                            Email = "bich.tt@uneti.com",
                            FullName = "Trần Thị Bích",
                            Gender = false,
                            StudentCode = "SV02"
                        },
                        new
                        {
                            StudentID = 3,
                            BirthDate = new DateTime(2002, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 2,
                            Email = "cuong.lh@yahoo.com",
                            FullName = "Lê Hoàng Cường",
                            Gender = true,
                            StudentCode = "SV03"
                        },
                        new
                        {
                            StudentID = 1004,
                            BirthDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 4,
                            Email = "tai@gmail.com",
                            FullName = "Nguyen trong tai",
                            Gender = true,
                            StudentCode = "SV04"
                        },
                        new
                        {
                            StudentID = 1005,
                            BirthDate = new DateTime(2005, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 5,
                            Email = "quan@gmail.com",
                            FullName = "Nguyen van quan",
                            Gender = true,
                            StudentCode = "SV05"
                        },
                        new
                        {
                            StudentID = 1006,
                            BirthDate = new DateTime(2005, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassID = 4,
                            Email = "lan@gmail.com",
                            FullName = "le dieu lan v2",
                            Gender = false,
                            StudentCode = "SV06"
                        });
                });

            modelBuilder.Entity("tuan3.models.StudentGrade", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StudentID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("StudentGrades");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            SubjectID = 3,
                            ExamDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 8.50m
                        },
                        new
                        {
                            StudentID = 2,
                            SubjectID = 3,
                            ExamDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 7.00m
                        },
                        new
                        {
                            StudentID = 2,
                            SubjectID = 4,
                            ExamDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 9.00m
                        },
                        new
                        {
                            StudentID = 2,
                            SubjectID = 5,
                            ExamDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 6.50m
                        },
                        new
                        {
                            StudentID = 3,
                            SubjectID = 5,
                            ExamDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 5.50m
                        });
                });

            modelBuilder.Entity("tuan3.models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<int?>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectID = 3,
                            Credits = 4,
                            SubjectCode = "CS101",
                            SubjectName = "Lập trình C#"
                        },
                        new
                        {
                            SubjectID = 4,
                            Credits = 4,
                            SubjectCode = "DB201",
                            SubjectName = "Cơ sở dữ liệu SQL Server"
                        },
                        new
                        {
                            SubjectID = 5,
                            Credits = 3,
                            SubjectCode = "WEB301",
                            SubjectName = "Phát triển ứng dụng Web"
                        },
                        new
                        {
                            SubjectID = 1002,
                            Credits = 2,
                            SubjectCode = "html",
                            SubjectName = "lập trình html"
                        },
                        new
                        {
                            SubjectID = 1003,
                            Credits = 2,
                            SubjectCode = "android",
                            SubjectName = "lập trình android"
                        });
                });

            modelBuilder.Entity("tuan3.models.Student", b =>
                {
                    b.HasOne("tuan3.models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("tuan3.models.StudentGrade", b =>
                {
                    b.HasOne("tuan3.models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tuan3.models.Subject", "Subject")
                        .WithMany("StudentGrades")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("tuan3.models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("tuan3.models.Subject", b =>
                {
                    b.Navigation("StudentGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
